/*
 * Name: server.rs
 * Purpose: Local HTTP REST API server for external automation.
 * Description: Binds to 127.0.0.1:8484 (localhost only). Opens its own
 *   read-only SQLite connection to avoid contending with the main
 *   app's Mutex. WAL mode enables concurrent readers. Runs in a
 *   background thread.
 * Tech Stack: Rust, tiny_http, serde_json
 * License: MIT
 * Authors: Amey Thakur (https://github.com/Amey-Thakur)
 *          Archit Konde (https://github.com/Archit-Konde)
 * Date: 2026-07-12
 */

use std::path::PathBuf;
use std::thread;

use rusqlite::Connection;
use tiny_http::{Header, Method, Response, Server};

use crate::database::repository::{
    chunk_repository, document_repository, note_repository, notebook_repository,
};

const API_PORT: u16 = 8484;
const CONTENT_TYPE_JSON: &str = "application/json";

/// Start the REST API server in a background thread.
/// Opens its own read-only database connection (WAL mode allows concurrent readers).
/// The session token is generated by AppState so the get_api_token command
/// and this server always agree on the credential.
pub fn start_api_server(db_path: PathBuf, api_token: String) {
    thread::spawn(move || {
        let expected_auth = format!("Bearer {}", api_token);
        let conn = match Connection::open_with_flags(
            &db_path,
            rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
        ) {
            Ok(c) => c,
            Err(e) => {
                tracing::warn!("REST API: could not open database: {e}");
                return;
            }
        };

        let addr = format!("127.0.0.1:{API_PORT}");
        let server = match Server::http(&addr) {
            Ok(s) => {
                tracing::info!("REST API server running at http://{addr}");
                s
            }
            Err(e) => {
                tracing::warn!("Could not start REST API server: {e}");
                return;
            }
        };

        for request in server.incoming_requests() {
            /* Verify bearer token (skip for /api/health which is public) */
            let path = request.url().split('?').next().unwrap_or("/");
            if path != "/api/health" {
                let auth_ok = request.headers().iter().any(|h| {
                    h.field.as_str() == "Authorization"
                        && constant_time_eq(h.value.as_str().as_bytes(), expected_auth.as_bytes())
                });
                if !auth_ok {
                    let header = Header::from_bytes("Content-Type", CONTENT_TYPE_JSON).unwrap();
                    let body = serde_json::json!({"error": "Unauthorized"}).to_string();
                    let r = Response::from_string(body)
                        .with_status_code(401)
                        .with_header(header);
                    request.respond(r).ok();
                    continue;
                }
            }

            let response = handle_request(&request, &conn);

            let header = Header::from_bytes("Content-Type", CONTENT_TYPE_JSON).unwrap();

            match response {
                Ok(body) => {
                    let r = Response::from_string(body).with_header(header);
                    request.respond(r).ok();
                }
                Err((status, msg)) => {
                    let error_json = serde_json::json!({ "error": msg }).to_string();
                    let r = Response::from_string(error_json)
                        .with_status_code(status)
                        .with_header(header);
                    request.respond(r).ok();
                }
            }
        }
    });
}

/// Compare two byte strings in constant time to avoid leaking the token
/// length-prefix through response timing. Local-only, but cheap to do right.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff: u8 = 0;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

fn handle_request(
    request: &tiny_http::Request,
    conn: &Connection,
) -> Result<String, (u16, String)> {
    let path = request.url().split('?').next().unwrap_or("/");
    let method = request.method();

    /* Repository errors are internal (500); unknown routes are 404 */
    let internal = |e: crate::error::AppError| (500u16, e.to_string());
    let encode = |e: serde_json::Error| (500u16, e.to_string());

    match (method, path) {
        (&Method::Get, "/api/health") => Ok(serde_json::json!({
            "status": "ok",
            "version": env!("CARGO_PKG_VERSION"),
            "api_port": API_PORT
        })
        .to_string()),

        (&Method::Get, "/api/notebooks") => {
            let notebooks = notebook_repository::list_all(conn).map_err(internal)?;
            serde_json::to_string(&notebooks).map_err(encode)
        }

        (&Method::Get, p) if p.starts_with("/api/notebooks/") && p.ends_with("/notes") => {
            let notebook_id = p
                .strip_prefix("/api/notebooks/")
                .and_then(|s| s.strip_suffix("/notes"))
                .unwrap_or("");
            let notes = note_repository::list_by_notebook(conn, notebook_id).map_err(internal)?;
            serde_json::to_string(&notes).map_err(encode)
        }

        (&Method::Get, p) if p.starts_with("/api/notebooks/") && p.ends_with("/documents") => {
            let notebook_id = p
                .strip_prefix("/api/notebooks/")
                .and_then(|s| s.strip_suffix("/documents"))
                .unwrap_or("");
            let docs =
                document_repository::list_by_notebook(conn, notebook_id).map_err(internal)?;
            serde_json::to_string(&docs).map_err(encode)
        }

        (&Method::Get, p) if p.starts_with("/api/documents/") && p.ends_with("/chunks") => {
            let doc_id = p
                .strip_prefix("/api/documents/")
                .and_then(|s| s.strip_suffix("/chunks"))
                .unwrap_or("");
            let chunks = chunk_repository::get_by_document(conn, doc_id).map_err(internal)?;
            serde_json::to_string(&chunks).map_err(encode)
        }

        (&Method::Get, "/api/chunks/count") => {
            let count = chunk_repository::count_all(conn).map_err(internal)?;
            Ok(serde_json::json!({ "count": count }).to_string())
        }

        _ => Err((404, format!("Not found: {} {}", method, path))),
    }
}
